crop_class_dict = {'salat': 'e2',
                   'mrkev': 'e6',
                   'redkvicka': 'e14',
                   'okurka': 'e12',
                   'jahoda': 'e3',
                   'rajce': 'e5',
                   'cibule': 'e9',
                   'spenat': 'e36',
                   'kvetak': 'e32',
                   'mesicek': 'e49',
                   'brambora': 'e22',
                   'cesnek': 'e35',
                   'paprika': 'e15',
                   'brokolice': 'e33',
                   'julinka je nejlepsi <3': '<3'}
